<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>BambiHeavy.PipelineTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\BambiHeavy\BambiHeavy.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2"/>
        <PackageReference Include="FluentAssertions" Version="6.12.1"/>
        <PackageReference Include="System.Drawing.Common" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Assets\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
        <Using Include="FluentAssertions"/>
        <Using Include="BambiHeavy.PipelineTests.Utilities"/>
        <Using Include="BambiHeavy.Models"/>
    </ItemGroup>

</Project>
